### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by brianamarie** [githubschool/july-25#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'unsubscribe' button.

**Comment by githubteacher** [comment]
Hello world!

**Comment by GillesThirion-DBG** [comment]
Great!

**Comment by anthonyc2018** [comment]
Just to be registered...

**Comment by OEthem** [comment]
Helloooo

**Comment by Belokan** [comment]
Hi

**Comment by ms9700** [comment]
Hello, its me

**Comment by ss929** [comment]
Hi

**Comment by bskou** [comment]
comment from bachir

**Comment by csterpin** [comment]
Hello

**Comment by cz333** [comment]
My irst comment on the issue tab ...

**Comment by dimgitws** [comment]
Taking the  5th

**Comment by kavurikb** [comment]
Its me.

**Comment by zavenger54** [comment]
hi
